version: '3'
services:
  zhishuyun-academy-frontend:
    container_name: 'zhishuyun-academy-frontend'
    build: ./
    image: 'ghcr.io/zhishuyun/zhishuyun-academy-frontend:${BUILD_NUMBER}'
    ports:
      - '8086:80'
