apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hub-frontend
  namespace: acedatacloud
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - hub.acedata.cloud
      secretName: tls-wildcard-acedata-cloud
  rules:
    - host: hub.acedata.cloud
      http:
        paths:
          - backend:
              serviceName: hub-frontend
              servicePort: 8083
            path: /
