apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-frontend
  name: chat-frontend
  namespace: zhishuyun
spec:
  ports:
    - name: '8083'
      port: 8083
      targetPort: 80
  selector:
    app: chat-frontend
