apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zhishuyun-frontend
  name: zhishuyun-frontend
  namespace: zhishuyun
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: zhishuyun-frontend
  template:
    metadata:
      labels:
        app: zhishuyun-frontend
    spec:
      containers:
        - image: zhishuyun/frontend:${TAG}
          name: zhishuyun-frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '200Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
      restartPolicy: Always
