name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - '.github/ISSUE_TEMPLATE/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test IP Address
        run: |
          wget -qO- https://ipecho.net/plain ; echo

      - name: Set Kubectl
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Test Kubectl
        run: |
          kubectl get nodes
          kubectl get svc -n zhishuyun-test

      - name: Generate build number
        run: |
          DATE=$(date +'%Y%m%d')
          echo "BUILD_NUMBER=$DATE.$(cat .build_number)" >> $GITHUB_ENV
          echo $(($(cat .build_number)+1)) > .build_number

      - name: Get Build Number
        run: |
          echo $BUILD_NUMBER

      - name: Build Push Deploy
        run: |
          docker-compose build
          docker-compose push
          sh ./deploy/test/scripts/deploy.sh
